apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 10s
              static_configs:
                - targets: ['0.0.0.0:8888']
      kafka:
        brokers: [kafka.observability.svc.cluster.local:9092]
        topic: otel-logs
        group_id: otel-collector-log-consumer
        client_id: otel-collector
    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      memory_limiter:
        limit_mib: 256
        check_interval: 1s
      resource:
        attributes:
          - key: environment
            value: "dev"
            action: insert
          - key: collector.version
            value: "1.0.0"
            action: insert
      attributes:
        actions:
          - key: http.user_agent
            action: delete
          - key: correlation.id
            from_attribute: trace_id
            action: insert
    exporters:
      otlp/jaeger:
        endpoint: jaeger-collector.observability.svc.cluster.local:4317
        tls:
          insecure: true
      prometheus:
        endpoint: "0.0.0.0:8889"
        const_labels:
          collector: "otel"
      elasticsearch:
        endpoints: ["http://elasticsearch.observability.svc.cluster.local:9200"]
        logs_index: "otel-logs"
        traces_index: "otel-traces"
      kafka/logs:
        brokers: [kafka.observability.svc.cluster.local:9092]
        topic: otel-logs
        encoding: otlp_proto
        retry_on_failure:
          enabled: true
        metadata:
          full: true
      logging:
        loglevel: debug
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      pprof:
        endpoint: 0.0.0.0:1777
      zpages:
        endpoint: 0.0.0.0:55679
    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, resource, attributes, batch]
          exporters: [otlp/jaeger, elasticsearch, logging]
        metrics:
          receivers: [otlp, prometheus]
          processors: [memory_limiter, resource, batch]
          exporters: [prometheus, logging]
        logs/produce:
          receivers: [otlp]
          processors: [memory_limiter, resource, attributes, batch]
          exporters: [kafka/logs, logging]
        logs/consume:
          receivers: [kafka]
          processors: [batch]
          exporters: [elasticsearch, logging]
      telemetry:
        logs:
          level: "debug"
        metrics:
          address: 0.0.0.0:8888
