apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: observability
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.example.com:587'
      smtp_from: 'alertmanager@yourcompany.com'
      smtp_auth_username: 'your-username-example'
      smtp_auth_password: 'your-password-example'
    route:
      group_by: ['alertname', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'default-receiver'
      routes:
        - match:
            severity: critical
          receiver: 'critical-alerts'
        - match:
            type: performance
          receiver: 'performance-alerts'
        - match:
            type: error_rate
          receiver: 'error-alerts'
    receivers:
      - name: 'default-receiver'
        webhook_configs:
          - url: 'https://your-webhook-endpoint.com/alerts'
            send_resolved: true
      - name: 'critical-alerts'
        webhook_configs:
          - url: 'https://your-webhook-endpoint.com/critical'
            send_resolved: true
      - name: 'performance-alerts'
        webhook_configs:
          - url: 'https://your-webhook-endpoint.com/performance'
            send_resolved: true
      - name: 'error-alerts'
        webhook_configs:
          - url: 'https://your-webhook-endpoint.com/errors'
            send_resolved: true
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'instance']
