global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  # Example: Application services (uncomment and customize for your services)
  # - job_name: 'your-app-service'
  #   static_configs:
  #     - targets: ['your-app-service:8080']
  #   metrics_path: '/metrics'
  #   scrape_interval: 15s

  # Example: Database metrics (uncomment and add appropriate exporter)
  # - job_name: 'database-exporter'
  #   static_configs:
  #     - targets: ['database-exporter:9187']
  #   scrape_interval: 15s
