version: '3.8'

services:
  o11y-python:
    build: .
    container_name: o11y-python
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_SERVICE_NAME=o11y-python
    networks:
      - observability
    ports:
      - "8000:8000"

  # Optional: sidecar/agent pattern (disabled by default)
  # otel-agent:
  #   image: otel/opentelemetry-collector-contrib:0.88.0
  #   command: ["--config=/etc/otel-agent-config.yaml"]
  #   volumes:
  #     - ./otel-agent-config.yaml:/etc/otel-agent-config.yaml
  #   networks:
  #     - observability

networks:
  observability:
    external: true
