apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-jmx-exporter
  namespace: observability
  labels:
    app: kafka-jmx-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-jmx-exporter
  template:
    metadata:
      labels:
        app: kafka-jmx-exporter
    spec:
      containers:
        - name: kafka-jmx-exporter
          image: bitnami/jmx-exporter:latest
          env:
            - name: JMX_EXPORTER_CONFIG_FILE
              value: /opt/bitnami/jmx-exporter/example_configs/kafka-2_0_0.yml
            - name: JMX_EXPORTER_JMX_URL
              value: service:jmx:rmi:///jndi/rmi://kafka-0.kafka.observability.svc.cluster.local:9999/jmxrmi
          ports:
            - name: metrics
              containerPort: 5556
