apiVersion: v1
kind: Service
metadata:
  name: kafka-jmx-exporter
  namespace: observability
  labels:
    app: kafka-jmx-exporter
spec:
  selector:
    app: kafka-jmx-exporter
  ports:
    - name: metrics
      port: 5556
      targetPort: 5556
