apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: observability
  labels:
    app: prometheus
    component: server
    part-of: observability-stack
    managed-by: kustomize
  annotations:
    checksum/config: ""
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    rule_files:
      - "/etc/prometheus/rules/*.yml"
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager.observability.svc.cluster.local:9093
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel-collector.observability.svc.cluster.local:8888']
      - job_name: 'otel-collector-exporter'
        static_configs:
          - targets: ['otel-collector.observability.svc.cluster.local:8889']
      - job_name: 'kafka'
        static_configs:
          - targets: ['kafka-jmx-exporter.observability.svc.cluster.local:5556']
      # Additional scrape jobs (node-exporter, app metrics) can be added by adding more scrape configs or ServiceMonitor CRDs if using Prometheus Operator.
