apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: observability
  labels:
    app: prometheus
    component: server
spec:
  selector:
    app: prometheus
    component: server
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      nodePort: 30900
  type: NodePort
